/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import java.text.DecimalFormat;

/**
 *
 * @author fance
 */
public class konversi extends javax.swing.JFrame {

    /**
     * Creates new form konversi
     */
    public konversi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jText1 = new javax.swing.JTextField();
        alatukur1 = new javax.swing.JComboBox();
        jText2 = new javax.swing.JTextField();
        alatukur2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("PROGRAM KONVERSI UNIT");

        jText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText1ActionPerformed(evt);
            }
        });

        alatukur1.setBackground(new java.awt.Color(153, 153, 255));
        alatukur1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Km", "Hm", "Dam", "M", "Dm", "Cm", "Mm" }));
        alatukur1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alatukur1MouseClicked(evt);
            }
        });
        alatukur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alatukur1ActionPerformed(evt);
            }
        });

        alatukur2.setBackground(new java.awt.Color(153, 153, 255));
        alatukur2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Km", "Hm", "Dam", "M", "Dm", "Cm", "Mm" }));
        alatukur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alatukur2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Masukkan Angka : ");

        jLabel2.setText("Ubah Ke :");

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jText2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alatukur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jText1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alatukur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alatukur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alatukur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alatukur1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alatukur1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_alatukur1MouseClicked

    private void alatukur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alatukur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alatukur1ActionPerformed

    //ini utk program utama perhitungan
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double a = Double.parseDouble(jText1.getText());
        double b;
        DecimalFormat df = new DecimalFormat();
        
        //Konversi KM
        if(alatukur1.getSelectedItem()=="Km"&&alatukur2.getSelectedItem()=="Km"){
            b=a;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Km"&&alatukur2.getSelectedItem()=="Hm"){
            b=a*10;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Km"&&alatukur2.getSelectedItem()=="Dam"){
            b=a*100;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Km"&&alatukur2.getSelectedItem()=="M"){
            b=a*1000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Km"&&alatukur2.getSelectedItem()=="Dm"){
            b=a*10000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Km"&&alatukur2.getSelectedItem()=="Cm"){
            b=a*100000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Km"&&alatukur2.getSelectedItem()=="Mm"){
            b=a*1000000;
            jText2.setText(""+df.format(b));
        }
        
        
        //Konversi HM
        if(alatukur1.getSelectedItem()=="Hm"&&alatukur2.getSelectedItem()=="Km"){
            b=a/10;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Hm"&&alatukur2.getSelectedItem()=="Hm"){
            b=a;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Hm"&&alatukur2.getSelectedItem()=="Dam"){
            b=a*10;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Hm"&&alatukur2.getSelectedItem()=="M"){
            b=a*100;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Hm"&&alatukur2.getSelectedItem()=="Dm"){
            b=a*1000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Hm"&&alatukur2.getSelectedItem()=="Cm"){
            b=a*10000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Hm"&&alatukur2.getSelectedItem()=="Mm"){
            b=a*100000;
            jText2.setText(""+df.format(b));
        }
        
        
        //Konversi DAM
        if(alatukur1.getSelectedItem()=="Dam"&&alatukur2.getSelectedItem()=="Km"){
            b=a/100;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Dam"&&alatukur2.getSelectedItem()=="Hm"){
            b=a/10;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Dam"&&alatukur2.getSelectedItem()=="Dam"){
            b=a;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Dam"&&alatukur2.getSelectedItem()=="M"){
            b=a*10;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Dam"&&alatukur2.getSelectedItem()=="Dm"){
            b=a*100;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Dam"&&alatukur2.getSelectedItem()=="Cm"){
            b=a*1000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Dam"&&alatukur2.getSelectedItem()=="Mm"){
            b=a*10000;
            jText2.setText(""+df.format(b));
        }
        
        
        //Konversi M
        if(alatukur1.getSelectedItem()=="M"&&alatukur2.getSelectedItem()=="Km"){
            b=a/1000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="M"&&alatukur2.getSelectedItem()=="Hm"){
            b=a/100;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="M"&&alatukur2.getSelectedItem()=="Dam"){
            b=a/10;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="M"&&alatukur2.getSelectedItem()=="M"){
            b=a;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="M"&&alatukur2.getSelectedItem()=="Dm"){
            b=a*10;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="M"&&alatukur2.getSelectedItem()=="Cm"){
            b=a*100;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="M"&&alatukur2.getSelectedItem()=="Mm"){
            b=a*1000;
            jText2.setText(""+df.format(b));
        }
        
        
        //Konversi DM
        if(alatukur1.getSelectedItem()=="Dm"&&alatukur2.getSelectedItem()=="Km"){
            b=a/10000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Dm"&&alatukur2.getSelectedItem()=="Hm"){
            b=a/1000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Dm"&&alatukur2.getSelectedItem()=="Dam"){
            b=a/100;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Dm"&&alatukur2.getSelectedItem()=="M"){
            b=a/10;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Dm"&&alatukur2.getSelectedItem()=="Dm"){
            b=a;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Dm"&&alatukur2.getSelectedItem()=="Cm"){
            b=a*10;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Dm"&&alatukur2.getSelectedItem()=="Mm"){
            b=a*100;
            jText2.setText(""+df.format(b));
        }
        
        
        //Konversi Cm
        if(alatukur1.getSelectedItem()=="Cm"&&alatukur2.getSelectedItem()=="Km"){
            b=a/100000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Cm"&&alatukur2.getSelectedItem()=="Hm"){
            b=a/10000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Cm"&&alatukur2.getSelectedItem()=="Dam"){
            b=a/1000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Cm"&&alatukur2.getSelectedItem()=="M"){
            b=a/100;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Cm"&&alatukur2.getSelectedItem()=="Dm"){
            b=a/10;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Cm"&&alatukur2.getSelectedItem()=="Cm"){
            b=a;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Cm"&&alatukur2.getSelectedItem()=="Mm"){
            b=a*10;
            jText2.setText(""+df.format(b));
        }
        
        
        //Konversi Mm
        if(alatukur1.getSelectedItem()=="Mm"&&alatukur2.getSelectedItem()=="Km"){
            b=a/1000000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Mm"&&alatukur2.getSelectedItem()=="Hm"){
            b=a/100000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Mm"&&alatukur2.getSelectedItem()=="Dam"){
            b=a/10000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Mm"&&alatukur2.getSelectedItem()=="M"){
            b=a/1000;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Mm"&&alatukur2.getSelectedItem()=="Dm"){
            b=a/100;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Mm"&&alatukur2.getSelectedItem()=="Cm"){
            b=a/10;
            jText2.setText(""+df.format(b));
        } else if(alatukur1.getSelectedItem()=="Mm"&&alatukur2.getSelectedItem()=="Mm"){
            b=a;
            jText2.setText(""+df.format(b));
        }
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText1ActionPerformed

    private void alatukur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alatukur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alatukur2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new konversi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox alatukur1;
    private javax.swing.JComboBox alatukur2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jText1;
    private javax.swing.JTextField jText2;
    // End of variables declaration//GEN-END:variables

    private void elseif(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
